<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>Themisquo.AspNetCore.Siren</PackageId>
    <RootNamespace>Themisquo.AspNetCore.Siren</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Themisquo.AspNetCore.Siren - Siren hypermedia responses for Themisquo endpoints</Title>
    <RepositoryUrl>https://github.com/TVolden/Themisquo</RepositoryUrl>
	<PackageIcon>Themisquo.png</PackageIcon>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	  <Authors>Thomas Volden</Authors>
    <Version>0.1.0</Version>
  </PropertyGroup>

	<ItemGroup>
		<None Include="..\Themisquo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Themisquo.AspNetCore\Themisquo.AspNetCore.csproj" />
  </ItemGroup>

</Project>
